apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-chart.fullname" . }}-ebs-mysql-pv-claim
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.ebsMysqlPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.ebsMysqlPvClaim.storageClass | quote }}
