apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.fullname" . }}-usermanagement-dbcreation-script
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
data:
  mysql_usermgmt.sql: {{ .Values.usermanagementDbcreationScript.mysqlUsermgmtSql
    | toYaml | indent 1 }}
