apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3                
  fsType: ext4             
  encrypted: "true"        
  kmsKeyId: "arn:aws:kms:ap-southeast-1:739089952409:key/98ac9ed1-f473-4020-a8bc-9edb1257b795"             
reclaimPolicy: Delete      
volumeBindingMode: WaitForFirstConsumer