name: Terraform Network

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Runs only when a PR is merged
  push:
    branches:
      - main
    paths:
      - 'backend/network/**/*.tf'  # Detects Terraform configuration file changes
      - 'backend/network/**/*.tfvars'  # Detects variable file changes
      - 'backend/network/terraform.lock.hcl'  # Detects lock file updates

jobs:
  terraform:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true  # Ensure job runs only when PR is merged

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mark repository as safe for Git
        run: git config --global --add safe.directory "$(pwd)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init & Validate
        run: |
          terraform init
          terraform validate
        working-directory: backend/network/

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: backend/network/

      - name: Terraform Apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve
        working-directory: backend/network/
